name: '✨ 기능 추가 (Feature Request)'
description: '구현할 기능을 기록합니다.'
title: '[Feat]: '
labels:
  - 'feat'
assignees:
  - 'sidamodev'
body:
  - type: input
    id: branch_slug
    attributes:
      label: Branch Slug (영문, kebab-case)
      placeholder: 예) write-page
      description: 브랜치명에 들어갈 짧은 영문 값을 입력해주세요.
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: 기능 설명
      placeholder: 무엇을 만들지 간단히 작성해주세요.
    validations:
      required: true

  - type: input
    id: done_criteria
    attributes:
      label: 완료 조건
      placeholder: 예) 해당 기능이 정상 동작하면 완료

  - type: textarea
    id: task_list
    attributes:
      label: 작업 목록
      value: |
        - [ ] 구현
        - [ ] 확인
