name: '♻️ 리팩토링 (Refactor)'
description: '리팩토링 작업을 기록합니다.'
title: '[Refactor]: '
labels:
  - 'refactor'
assignees:
  - 'sidamodev'
body:
  - type: input
    id: branch_slug
    attributes:
      label: Branch Slug (영문, kebab-case)
      placeholder: 예) simplify-post-service
      description: 브랜치명에 들어갈 짧은 영문 값을 입력해주세요.
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 변경 목적
      placeholder: 왜 바꾸는지 간단히 작성해주세요.
    validations:
      required: true

  - type: input
    id: done_criteria
    attributes:
      label: 완료 조건
      placeholder: 예) 리팩토링 후 기존 동작과 동일하면 완료

  - type: textarea
    id: task_list
    attributes:
      label: 작업 목록
      value: |
        - [ ] 리팩토링
        - [ ] 확인
